### ISSUE TITLE
Dúvida para setar vlan

### ISSUE THREAD

**Issue by AndrelsFlor** [davibaltar/snmp-fiberhome#1]
Olá, estou tentando usar o método addOnu() e, embora ele sempre autorize corretamente a ONU, a VLAN nunca é setada. O trecho de código é o seguinte:

const options = {
                ip,
                community: 'Community',
                port: 161,
                trapPort: 162,
                enableWarnings: true,
                enableLogs: true,
            };

            const wanProfile = [];
            const lanProfile = [
                {
                    lanPort: 1,
                    vlans: [{ vlanMode: 'tag', cvlanId: 400, cos: 0 }],
                },
            ];
            const unauth = await fh.getUnauthorizedOnus(options);
            const onu = unauth.filter(
                i => i.macAddress.toLowerCase() === mac.toLowerCase()
            )[0];

            const result = await fh.addOnu(
                options,
                onu,
                wanProfile,
                lanProfile
            );

Poderia  me dizer se estou fazendo algo errado?

**Comment by davibaltar** [comment]
Olá, André. Testei esses parâmetros aqui na minha ONU AN5506-01-A1 e AN5506-04-F1, e funcionou. Posta o como tah ficando o seu console.log(onu) antes de chamar o 'fh.addOnu(...)' pra eu verificar. E me fala qual o modelo da sua ONU.

**Comment by AndrelsFlor** [comment]
Olá. Constatei que o problema só está ocorrendo em cards EPON. o console.log(onu) me devolve o seguinte objeto:

{ index: 0,
  slot: 12,
  pon: 16,
  onuType:
   { code: 785,
     category: 'SFU',
     model: 'AN5506-01-A1',
     type: 'GPON',
     mode: 'bridge' },
  macAddress: 'DD1Bb3cbd138' }

**Comment by davibaltar** [comment]
ah sim. Até o momento o desenvolvimento e os testes foram feitos somente com GPON. A EPON está em desenvolvimento ainda. Então, fica de olho no repositório, pq isso não deve demorar. Inclusive vou colocar essa observação na descrição.

**Comment by davibaltar** [comment]
Problema resolvido na versão 1.1.4. As funções 'setLanPorts()' e 'getLanPorts()' agora reconhecem EPON e GPON.
