### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by dayvydplussystem** [davibaltar/snmp-fiberhome#2]
Boa noite, Davi.

Existe alguma documentação da Fiberhome com parâmetros? Se sim, poderia postar no Wiki.

Pra TL1 sei que existe!

Obrigado

**Comment by davibaltar** [comment]
Olá, Dayvyd. 

Eu tenho uma documentação aqui pra SNMP, porém, ela não está 100% correta. Se tiver interesse, deixa seu e-mail aqui que eu te envio.

E não disponibilizei na Wiki por que algumas coisas ainda estou estudando sobre a comunicação com o equipamento. Pra vc ter uma idea, algumas informações (como o sinal rx, por exemplo) são obtidas via 'set' passando um protocolo, e isso não está na documentação. Mas assim que eu terminar esse estudo eu pretendo documentar sim. 

Att

**Comment by dayvydplussystem** [comment]
Bom dia, Davi.

Se possível envie para o email dayvydplussystem@gmail.com

Obrigado.

**Comment by davibaltar** [comment]
Bom dia. Te enviei lah.

**Comment by daniloacrz** [comment]
Primeiramente, parabéns pelo projeto! Muito top!

Poderia compartilhar comigo também?
daniloacr@gmail.com
