### ISSUE TITLE
[Feature] VEIP Data Service Config

### ISSUE THREAD

**Issue by jjsquady** [davibaltar/snmp-fiberhome#4]
Hi Davi! 
Do you know of the possibility to add VEIP Data Service Profile configuration via SNMP?

**Comment by davibaltar** [comment]
Hi Jorge.

Thank you for the contact. But at the moment, we have no plans to implement VEIP. At the moment, the focus is on performance gain in the functions already implemented. But in the future we may see the possibility of implementing yes.

**Comment by HCDestroyer** [comment]
How implement VEIP on package?
