### ISSUE TITLE
Nome da community no modelo AN5506-04-F

### ISSUE THREAD

**Issue by carlosfilhoadm** [davibaltar/snmp-fiberhome#5]
Olá Davi,

Estou tentando acessar o GPON AN5506-04-F via SNMP, porém não tenho idéia do nome da community do aparelho. Já tentei os nomes mais comuns utilizados em outros roteadores (community, default, public), mas sem sucesso.

Você conhece, ou tem alguma sugestão de quais outros nomes tentar? As especificações do aparelho são:

Software Version: RP2613
Hardware Version: WKE2.134.285FAT1
Device Model: AN5506-04-F

Obrigado, um abraço.

**Comment by davibaltar** [comment]
Boa tarde, Carlos. Infelizmente eu não tenho essa informação.

Att
