### ISSUE TITLE
Problema com communities muito grandes

### ISSUE THREAD

**Issue by AndrelsFlor** [davibaltar/snmp-fiberhome#6]
Olá, a maioria das OLTs que eu monitoro possuem uma community de apenas 4 caracteres e nunca tive problemas com elas. Recentemente, passei a monitorar algumas cujas communites possuem algo em torno de 11 caracteres. Para todos as requisições do tipo GET, não houve problema algum. No entanto, para as requisições do tipo SET, comecei a ter problemas e, após analisar o tcpdump, percebi que a community que está chegando é a "63_6b_74_35_38_39_39_31_36_30_36_a3_82_01_22_02_02 [id?P/x/24]", que não é o valor da community de fato. Tentei consertar isso sozinho, porém não entendio muito bem o funcionamento da função "createPackage" que o sendSnmp chama e fiquei "empacado". Obrigado pela atenção!

**Comment by davibaltar** [comment]
Olá André. Pelo que analisei no código acredito que o problema está na falta de conversão do tamanho da community (de DEC para HEX) no pacote, por isso que senhas com até 9 caracteres não tinham problemas. 

Faz um teste na sua maquina, por favor, no arquivo './src/pack-fiberhome.js', linha: 126, substitua toda essa linha por:

raw += `${dataType.OctetString} ${(objSNMP.community.strToHex().replaceAll(' ', '').split('').length / 2).toHex(2)} ${objSNMP.community.strToHex()}`       // COMMUNITY: <tipo> | <tamanho> | <community>


Me fala aqui se der certo, que eu faço uma publicação com essa correção.

Att

**Comment by davibaltar** [comment]
Olá André. Pelo que analisei no código, acredito que o problema está na falta de conversão do tamanho da community (de DEC para HEX) no pacote, por isso que senhas com até 9 caracteres não tinham problemas. 

Faz um teste na sua maquina, por favor, no arquivo './src/pack-fiberhome.js', linha: 126, substitua toda essa linha por:

`
raw += `${dataType.OctetString} ${(objSNMP.community.strToHex().replaceAll(' ', '').split('').length / 2).toHex(2)} ${objSNMP.community.strToHex()}`       // COMMUNITY: <tipo> | <tamanho> | <community>
`

Me fala aqui se der certo, que eu faço uma publicação com essa correção.

Att

**Comment by davibaltar** [comment]
Olá André. Pelo que analisei no código, acredito que o problema está na falta de conversão do tamanho da community (de DEC para HEX) no pacote, por isso que senhas com até 9 caracteres não tinham problemas. 

Faz um teste na sua maquina, por favor, no arquivo './src/pack-fiberhome.js', linha: 126, substitua toda essa linha por:

`
raw += ``${dataType.OctetString} ${(objSNMP.community.strToHex().replaceAll(' ', '').split('').length / 2).toHex(2)} ${objSNMP.community.strToHex()}``       // COMMUNITY: <tipo> | <tamanho> | <community>
`


Me fala aqui se der certo, que eu faço uma publicação com essa correção.

Att

**Comment by AndrelsFlor** [comment]
Davi, com essa alteração que você sugeriu, o problema foi corrigido. Muito obrigado!

**Comment by davibaltar** [comment]
Ótimo! Por nada. Depois vou publicar essa correção.
