### ISSUE TITLE
Problema ao retornar portas lan da ONU

### ISSUE THREAD

**Issue by rafaelcorreiapaz** [davibaltar/snmp-fiberhome#7]
Estou tenho problemas eu retornar as portas lan da ONU. Sempre retorna false.

**Comment by davibaltar** [comment]
Oi Rafael. Hoje não tenho mais um ambiente de teste (com OLT e ONU) e por esse motivo o módulo foi descontinuado. Infelizmente não vou conseguir te ajudar.

Att
